config/routes.rb
Rails.application.routes.draw do

  # sidekiq monitoring
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(username, 'sidekiq') &
        ActiveSupport::SecurityUtils.secure_compare(password, ENV['SIDEKIQ_PASSWORD'])
  end
  mount Sidekiq::Web, at: "/sidekiq"

  # back-offices
  ActiveAdmin.routes(self)

  # authentication
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  # public-routes
  root to: 'home#show'
  resources :subscription_request
  resources :user, path: 'private', except: [:index] do
    resources :search, only: [:index] do
      collection do
        get :recherche
      end
    end
    get '/dashboard', to: "dashboard#index"
    resources :favorite, except: [:new, :create]
    resources :comment, only: [:index]
    resources :calendar, only: [:index]
    resources :restaurant, only: :show do
      resources :comments, only: [:index, :new, :create]
    end
  end
  post '/event', to: "event#create"
  post '/favorite', to: "favorite#create"
  get '/restaurant/:id', to: "restaurant#show"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(current_user)
    current_user ||= User.new
    can :manage, Search, user_id: current_user.id
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  validates :body, presence: true
end

app/models/dashboard.rb
# frozen_string_literal: true

class Dashboard < ApplicationRecord
  belongs_to :user
end

app/models/department.rb
# frozen_string_literal: true

class Department < ApplicationRecord
  validates :name, :zip_code, presence: true, uniqueness: true
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  belongs_to :restaurant
  validates_uniqueness_of :title, scope: :restaurant_id
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :title, :date, presence: true
  belongs_to :restaurant
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  validates_uniqueness_of :restaurant, scope: :user_id
  belongs_to :restaurant
  belongs_to :user
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :dishes, dependent: :destroy
  validates :name, :slug, presence: true, uniqueness: true

  geocoded_by :full_address
  after_validation :geocode, if: ->(obj) { obj.full_address.present? && obj.full_address_changed? }

  def first_three_tags
    tags.first(3)
  end
end

app/models/restaurant_menu.rb
# frozen_string_literal: true

class RestaurantMenu < ApplicationRecord
  belongs_to :restaurant
  has_many :dishes
  validates :restaurant_id, uniqueness: true
end

app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
  belongs_to :user
end

app/models/subscription_request.rb
# frozen_string_literal: true

class SubscriptionRequest < ApplicationRecord
  validates :last_name, :first_name, :company, :prospecting_area, presence: true
  validates :email, uniqueness: true, presence: true
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :role, presence: true
  has_many :work_areas
  has_many :departments, through: :work_areas
  belongs_to :team, optional: true
  accepts_nested_attributes_for :work_areas, allow_destroy: true

  enum role: { manager: 0, commercial: 1 }

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/models/work_area.rb
# frozen_string_literal: true

class WorkArea < ApplicationRecord
  belongs_to :user
  belongs_to :department
end

app/controllers/event_controller.rb
# frozen_string_literal: true

class EventController < ApplicationController
  skip_before_action :verify_authenticity_token

  layout 'private'

  def create
    event = Event.create!(event_params)
    render json: event
  end

  private

  def event_params
    params.require(:event).permit(:title, :id, :user_id, :restaurant_id, :date)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  layout 'homepage'

  def show; end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="brown darken-1">
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><%= link_to 'Concept' %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Dashboard', user_dashboard_index_path(current_user) %></li>
        <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Connexion', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><%= link_to 'Concept' %></li>
  <% if user_signed_in? %>
    <li><%= link_to 'Dashboard', user_dashboard_index_path(current_user) %></li>
    <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Connexion', new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Manjari|Anton|Poiret+One|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>
    <%= flash[:message] %>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>

app/views/layouts/homepage.html.erb
<%= react_component 'navigation/PublicNavbar', userSignedIn: user_signed_in?, currentUser: current_user%>

<% content_for :content do %>
  <%= content_for?(:homepage_content) ? yield(:homepage_content) : yield %>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/private.html.erb
<%= react_component('navigation/PrivateNavbar', {userId: current_user.id}) %>

<% content_for :content do %>
  <%= content_for?(:users_content) ? yield(:users_content) : yield %>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/users.html.erb
<%= react_component('navigation/PrivateNavbar', {userId: current_user.id}) %>

<% content_for :content do %>
  <%= content_for?(:users_content) ? yield(:users_content) : yield %>
<% end %>

<%= render template: "layouts/application" %>